// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgNHKt6OJL_-ygC9uK2T69KwZIdSMsBGA',
    appId: '1:520706337895:web:24914ce2dacff81c0f38c2',
    messagingSenderId: '520706337895',
    projectId: 'contentmanagement-2080b',
    authDomain: 'contentmanagement-2080b.firebaseapp.com',
    storageBucket: 'contentmanagement-2080b.firebasestorage.app',
    measurementId: 'G-15WZC2F62M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPw6gKUSOQQRHeMcl7BLPtcIIFqvA4XwY',
    appId: '1:520706337895:android:04ce39da05af733f0f38c2',
    messagingSenderId: '520706337895',
    projectId: 'contentmanagement-2080b',
    storageBucket: 'contentmanagement-2080b.firebasestorage.app',
  );

}